# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.TextField(max_length=10000, verbose_name='About')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Personal website')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Url')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook Url')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter Url')),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
