# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation'),
        ),
    ]
