# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image height'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=profiles.models.profile_photo_upload_location, verbose_name='Screenshot', width_field='width'),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image width'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
    ]
