# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170918_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='about',
        ),
    ]
