# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_auto_20170927_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_profile_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='datetime_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First published on'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_profile_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='profile',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_profile_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=profiles.models.profile_photo_upload_location, verbose_name='Screen shot', width_field='width'),
        ),
    ]
