# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20171005_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
    ]
