# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(max_length=5000, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(max_length=1500, verbose_name='Short description'),
        ),
    ]
