# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20170921_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectattachment',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='projectattachment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='user',
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectattachment_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='datetime_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First published on'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectattachment_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectattachment_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by'),
        ),
        migrations.AddField(
            model_name='projectlink',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectlink_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectlink',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectlink',
            name='datetime_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First published on'),
        ),
        migrations.AddField(
            model_name='projectlink',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectlink_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='projectlink',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectlink_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by'),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
    ]
