# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170921_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='full_description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='projectlink',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
