# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170921_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Content body'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill', verbose_name='Related skills'),
        ),
    ]
