# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='projectattachment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='slug',
        ),
    ]
