# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multimedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('datetime_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified on')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('datetime_published', models.DateTimeField(blank=True, null=True, verbose_name='First published on')),
                ('file', models.FileField(upload_to=multimedia.models.upload_file_location, verbose_name='File')),
                ('title', models.CharField(max_length=50, verbose_name='Attachment name')),
                ('description', models.CharField(max_length=1500, verbose_name='Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_file_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_file_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_file_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('datetime_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified on')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('datetime_published', models.DateTimeField(blank=True, null=True, verbose_name='First published on')),
                ('title', models.CharField(max_length=50, verbose_name='Image name')),
                ('description', models.CharField(max_length=1500, verbose_name='Description')),
                ('image', models.ImageField(height_field='height', upload_to=multimedia.models.upload_image_location, verbose_name='Image', width_field='width')),
                ('width', models.IntegerField(verbose_name='Image width')),
                ('height', models.IntegerField(verbose_name='Image height')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image?')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_image_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_image_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_image_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('datetime_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified on')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
                ('datetime_published', models.DateTimeField(blank=True, null=True, verbose_name='First published on')),
                ('title', models.CharField(max_length=50, verbose_name='Link name')),
                ('description', models.CharField(max_length=1500)),
                ('url', models.URLField(max_length=255, verbose_name='Url')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_link_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_link_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_link_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
