# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_requestcount_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcount',
            old_name='count',
            new_name='hit_count',
        ),
    ]
