# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170820_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactReceiver',
        ),
    ]
