# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_delete_contactreceiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='First name'),
            preserve_default=False,
        ),
    ]
