# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20170911_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
