# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20170911_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization name'),
        ),
    ]
