# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'LOVE'), (1, 'CAKE'), (2, 'THUMBS_UP'), (3, 'THUMBS_DOWN')], default=0, verbose_name='Vote rating')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comment')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Voter's name")),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Address')),
                ('hide_comment', models.BooleanField(default=False, verbose_name='Hide comment')),
                ('cancel_vote', models.BooleanField(default=False, verbose_name='Cancel vote')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
