# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('votes', '0002_auto_20170830_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(0, 'LOVE'), (1, 'THUMBS_UP'), (2, 'THUMBS_DOWN')], default=0, verbose_name='Vote rating'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('content_type', 'object_id', 'ip_address')]),
        ),
    ]
