# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20170831_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='cancel_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='hide_comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
        migrations.AddField(
            model_name='vote',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
