# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebase',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 3, 9, 56, 8, 7584), verbose_name='Added on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumebase',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified on'),
        ),
    ]
