# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170903_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
