# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170903_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.AlterField(
            model_name='work',
            name='date_till',
            field=models.DateField(blank=True, null=True, verbose_name='Till'),
        ),
    ]
