# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170903_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Image height'),
        ),
        migrations.AddField(
            model_name='work',
            name='organization_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=resume.models.work_image_upload_location, verbose_name='Organization logo', width_field='width'),
        ),
        migrations.AddField(
            model_name='work',
            name='width',
            field=models.IntegerField(null=True, verbose_name='Image width'),
        ),
    ]
