# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimage',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date added'),
            preserve_default=False,
        ),
    ]
