# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0007_workimage_datetime_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Image?'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
            preserve_default=False,
        ),
    ]
