# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20170904_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(default='asdf', height_field='height', upload_to=resume.models.work_image_upload_location, verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
    ]
