# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0010_auto_20170921_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.AddField(
            model_name='resumebase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
            preserve_default=False,
        ),
    ]
