# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0011_auto_20170921_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumebase',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='resumebase',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='resumebase',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='resumebase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workimage',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='workimage',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='workimage',
            name='user',
        ),
        migrations.AddField(
            model_name='resumebase',
            name='content',
            field=models.TextField(default='content', max_length=5000, verbose_name='Content body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumebase',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume_resumebase_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumebase',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumebase',
            name='datetime_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First published on'),
        ),
        migrations.AddField(
            model_name='resumebase',
            name='description',
            field=models.TextField(default='description', max_length=1500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumebase',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_resumebase_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='resumebase',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_resumebase_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by'),
        ),
        migrations.AlterField(
            model_name='resumebase',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Project title'),
        ),
    ]
