# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0012_auto_20170921_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimage',
            name='datetime_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First published on'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_workimage_publish_related', to=settings.AUTH_USER_MODEL, verbose_name='First published by'),
        ),
    ]
