# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0013_auto_20170921_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume_workimage_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workimage',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workimage',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modified on'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='description',
            field=models.CharField(default='description', max_length=1500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workimage',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_workimage_modified_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Image name'),
            preserve_default=False,
        ),
    ]
