# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20170921_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumebase',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
    ]
