# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import skills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Skill title')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short description')),
                ('full_description', models.CharField(max_length=5000, verbose_name='Full description')),
                ('level_max', models.IntegerField(default=5, verbose_name='Level caps')),
                ('level', models.IntegerField(verbose_name='Current skill level')),
                ('is_published', models.BooleanField(verbose_name='Is published?')),
                ('icon', models.ImageField(blank=True, height_field='height', null=True, upload_to=skills.models.skill_image_upload_location, verbose_name='Icon', width_field='width')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Icon width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Icon height')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified on')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('frontend_position', models.IntegerField(verbose_name='Position on frontend')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.SkillCategory'),
        ),
    ]
