# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20170809_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='full_description',
            field=models.TextField(max_length=5000, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image height'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=skills.models.skill_image_upload_location, verbose_name='Plaatje', width_field='width'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image width'),
        ),
    ]
