# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20170813_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='short_description',
            field=models.TextField(max_length=2000, verbose_name='Short description'),
        ),
    ]
