# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20170813_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=skills.models.skill_image_upload_location, verbose_name='Image', width_field='width'),
        ),
    ]
