# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_auto_20170911_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
    ]
