# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20170921_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level_max',
            field=models.IntegerField(default=10, verbose_name='Level caps'),
        ),
    ]
